export const ActionTypes = {
  SEARCH_ACTIONS: {
    SET_SEARCH_RESULT: "SET_SEARCH_RESULT",
    SET_SEARCH_TYPE:"SET_SEARCH_TYPE",
    SET_SEARCH_TEXT:"SET_SEARCH_TEXT",
    SET_SEARCH_PAGE_NUMBER:"SET_SEARCH_PAGE_NUMBER",
    SET_SEARCH_TOTAL_COUNT:"SET_SEARCH_TOTAL_COUNT"
  }
};

export default ActionTypes;
